import { MenuItem, Review } from './types';
// @ts-ignore
import multiMilletDosaImg from './assets/images/multi_millet_dosa_1784042383629.jpg';
// @ts-ignore
import carrotDosaImg from './assets/images/carrot_dosa_updated_1784043110377.jpg';
// @ts-ignore
import beetrootDosaImg from './assets/images/beetroot_dosa_updated_1784043327660.jpg';
// @ts-ignore
import spinachDosaImg from './assets/images/spinach_dosa_updated_1784043465519.jpg';
// @ts-ignore
import eggDosaImg from './assets/images/egg_dosa_updated_1784043818742.jpg';
// @ts-ignore
import doubleEggDosaImg from './assets/images/double_egg_dosa_1784045637054.jpg';
// @ts-ignore
import teaImg from './assets/images/tea_updated_1784046051560.jpg';
// @ts-ignore
import coffeeImg from './assets/images/coffee_updated_1784046347174.jpg';
// @ts-ignore
import bellamTeaImg from './assets/images/bellam_tea_updated_1784046925900.jpg';
// @ts-ignore
import badamTeaImg from './assets/images/badam_tea_updated_1784047093178.jpg';
// @ts-ignore
import greenTeaImg from './assets/images/green_tea_updated_1784047409836.jpg';
// @ts-ignore
import horlicksBoostImg from './assets/images/horlicks_boost_updated_1784047847476.jpg';
// @ts-ignore
import ragiMaltImg from './assets/images/ragi_malt_updated_1784048040741.jpg';
// @ts-ignore
import bananaIcecreamShakeImg from './assets/images/banana_icecream_shake_1784048439834.jpg';
// @ts-ignore
import bananaKajuJuiceImg from './assets/images/banana_kaju_juice_1784049443616.jpg';
// @ts-ignore
import badhamMilkOfficialImg from './assets/images/badham_milk_official_1784611871934.jpg';
// @ts-ignore
import watermelonJuiceOfficialImg from './assets/images/watermelon_juice_official_1784709243822.jpg';
// @ts-ignore
import roseMilkOfficialImg from './assets/images/rose_milk_official_1785478783760.jpg';
// @ts-ignore
import paneerRollImg from './assets/images/paneer_roll_updated_1785733634954.jpg';

export const MENU_ITEMS: MenuItem[] = [
  // --- MORNING BREAKFAST ---
  {
    id: 'm1',
    name: 'Multi Millet Dosa',
    description: 'Crispy, high-fiber South Indian crepe made with five healthy organic millets. Served with fresh coconut and spicy tomato chutneys.',
    price: 25,
    image: multiMilletDosaImg,
    category: 'breakfast',
    calories: 180,
    protein: 6,
    carbs: 32,
    fats: 3,
    rating: 4.9,
    ingredients: ['Ragi', 'Bajra', 'Jowar', 'Foxtail Millet', 'Urad Dal', 'Coconut Chutney'],
    tags: ['Millet Power', 'Gluten-Free', 'High Fiber', 'Best Seller'],
    isFeatured: true,
  },
  {
    id: 'm2',
    name: 'Carrot Dosa',
    description: 'Naturally sweet and highly nutritious golden crepe enriched with fresh organic grated carrots. Packed with Beta-Carotene.',
    price: 25,
    image: carrotDosaImg,
    category: 'breakfast',
    calories: 195,
    protein: 5,
    carbs: 36,
    fats: 3.5,
    rating: 4.7,
    ingredients: ['Fresh Carrot', 'Rice Batter', 'Urad Dal', 'Cumin Seeds', 'Chutney'],
    tags: ['Vitamin-A Rich', 'Kids Favorite', 'Healthy Glow'],
    isFeatured: false,
  },
  {
    id: 'm3',
    name: 'Beetroot Dosa',
    description: 'A vibrant ruby-red, naturally sweet and iron-rich crepe prepared with fresh beetroot puree. Served warm with artisanal chutneys.',
    price: 25,
    image: beetrootDosaImg,
    category: 'breakfast',
    calories: 190,
    protein: 5,
    carbs: 35,
    fats: 3,
    rating: 4.8,
    ingredients: ['Fresh Beetroot', 'Dosa Batter', 'Ginger Accent', 'Chutney Combo'],
    tags: ['Iron Booster', 'Antioxidant', 'Visually Stunning'],
    isFeatured: true,
  },
  {
    id: 'm4',
    name: 'Spinach Dosa',
    description: 'Vibrant green, iron-packed crepe made with fresh local spinach paste and mild aromatic spices. Perfect clean breakfast choice.',
    price: 25,
    image: spinachDosaImg,
    category: 'breakfast',
    calories: 185,
    protein: 5.5,
    carbs: 31,
    fats: 3,
    rating: 4.7,
    ingredients: ['Spinach Leaves', 'Dosa Batter', 'Green Chilies', 'Cumin', 'Chutney'],
    tags: ['Palak Energy', 'High Iron', 'Detox Breakfast'],
    isFeatured: false,
  },
  {
    id: 'm5',
    name: 'Egg Dosa',
    description: 'A crispy premium breakfast crepe topped with a seasoned whisked egg layer and cracked black pepper. A classic morning favorite.',
    price: 35,
    image: eggDosaImg,
    category: 'breakfast',
    calories: 270,
    protein: 13,
    carbs: 29,
    fats: 9,
    rating: 4.8,
    ingredients: ['Whole Egg', 'Dosa Batter', 'Black Pepper', 'Onions', 'Spices'],
    tags: ['High Protein', 'Morning Energy', 'Satisfying'],
    isFeatured: false,
  },
  {
    id: 'm6',
    name: 'Double Egg Dosa',
    description: 'Double the protein! A thick, incredibly satisfying dosa coated with two farm-fresh whipped eggs and ground black pepper.',
    price: 40,
    image: doubleEggDosaImg,
    category: 'breakfast',
    calories: 345,
    protein: 19,
    carbs: 29,
    fats: 14,
    rating: 4.9,
    ingredients: ['Two Eggs', 'Dosa Batter', 'Black Pepper', 'Onions', 'Chutney'],
    tags: ['Extreme Protein', 'Gym Recovery', 'Best Seller'],
    isFeatured: true,
  },

  // --- EVENING SNACKS ---
  {
    id: 'm7',
    name: 'Veg Sandwich',
    description: 'Lightly toasted multi-grain bread stuffed with crisp local cucumbers, tomatoes, bell peppers, and low-fat herbal spread.',
    price: 40,
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 210,
    protein: 6,
    carbs: 34,
    fats: 4,
    rating: 4.6,
    ingredients: ['Multi-grain Bread', 'Cucumber', 'Tomato', 'Bell Peppers', 'Mint Yogurt Spread'],
    tags: ['Low Calorie', '100% Veg', 'Teatime Favorite'],
    isFeatured: false,
  },
  {
    id: 'm8',
    name: 'Chicken Sandwich',
    description: 'Lean shredded chicken breast tossed in organic black pepper and a light yogurt dressing, grilled inside high-fiber whole wheat bread.',
    price: 50,
    image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 320,
    protein: 24,
    carbs: 30,
    fats: 8,
    rating: 4.8,
    ingredients: ['Chicken Breast', 'Whole Wheat Bread', 'Greek Yogurt Dressing', 'Black Pepper'],
    tags: ['High Protein', 'Lean Snack', 'Muscle Builder'],
    isFeatured: true,
  },
  {
    id: 'm9',
    name: 'Egg Roll',
    description: 'Soft and healthy whole wheat paratha wrap layered with a fluffy cooked egg, fresh julienned onion salad, and dynamic lime.',
    price: 40,
    image: 'https://images.unsplash.com/photo-1626700051175-6518c4793f4f?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 280,
    protein: 11,
    carbs: 32,
    fats: 9,
    rating: 4.7,
    ingredients: ['Whole Wheat Wrap', 'One Egg', 'Sliced Onions', 'Tangy Lemon Juice', 'Spices'],
    tags: ['Quick Bite', 'Handheld Fuel', 'Freshly Rolled'],
    isFeatured: false,
  },
  {
    id: 'm10',
    name: 'Paneer Roll',
    description: 'Rich, spiced paneer (cottage cheese) cubes grilled to perfection, wrapped inside a fiber-dense wheat flatbread with green chutney.',
    price: 50,
    image: paneerRollImg,
    category: 'snacks',
    calories: 340,
    protein: 14,
    carbs: 36,
    fats: 12,
    rating: 4.8,
    ingredients: ['Low-fat Paneer', 'Whole Wheat Roti', 'Mint Chutney', 'Onions & Capsicum'],
    tags: ['High Protein Veg', 'Rich & Savory', 'Campus Special'],
    isFeatured: true,
  },
  {
    id: 'm11',
    name: 'Chicken Roll',
    description: 'Succulent spiced grilled chicken chunks rolled into a warm healthy wheat flatbread, layered with zesty mint-coriander chutney.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 360,
    protein: 22,
    carbs: 34,
    fats: 11,
    rating: 4.9,
    ingredients: ['Grilled Chicken Chunks', 'Wheat Flatbread', 'Mint-Coriander Chutney', 'Lemon juice'],
    tags: ['High Protein', 'Post-workout', 'Best Seller'],
    isFeatured: true,
  },
  {
    id: 'm12',
    name: 'Bread Omlette',
    description: 'Street-style comfort snack with pan-toasted whole wheat bread slices surrounding a fluffy, finely spiced egg omelette.',
    price: 30,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 290,
    protein: 12,
    carbs: 28,
    fats: 10,
    rating: 4.7,
    ingredients: ['Whole Wheat Bread', 'One Egg', 'Chopped Onions', 'Green Chilies', 'Pepper'],
    tags: ['Teatime Snack', 'Comfort Food', 'Instantly Cooked'],
    isFeatured: false,
  },
  {
    id: 'm13',
    name: 'Spinach Omlette',
    description: 'Fluffy egg omelette fortified with chopped fresh local baby spinach, minced green chilies, coriander leaves, and fine spices.',
    price: 30,
    image: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 160,
    protein: 11,
    carbs: 4,
    fats: 9,
    rating: 4.6,
    ingredients: ['Fresh Spinach', 'Egg', 'Green Chilies', 'Coriander', 'Indian Herbs'],
    tags: ['Iron Fortified', 'Low Carb Keto', 'Super Clean'],
    isFeatured: false,
  },
  {
    id: 'm14',
    name: 'Double Egg Omlette',
    description: 'A robust double-egg omelette prepared with freshly diced red onions, crisp green chilies, herbs, and coarse black pepper.',
    price: 30,
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 230,
    protein: 18,
    carbs: 5,
    fats: 14,
    rating: 4.8,
    ingredients: ['Two Eggs', 'Red Onions', 'Green Chilies', 'Fresh Herbs', 'Black Pepper'],
    tags: ['High Protein', 'Keto Approved', 'Simple Nutrition'],
    isFeatured: false,
  },
  {
    id: 'm15',
    name: 'Pani Puri (6)',
    description: 'Crisp whole-wheat puris filled with spicy boiled potato mash and dunked in fresh herbal mint-coriander and tamarind water.',
    price: 25,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600',
    category: 'snacks',
    calories: 140,
    protein: 3,
    carbs: 28,
    fats: 1.5,
    rating: 4.9,
    ingredients: ['Wheat Puris', 'Mashed Potato & Chickpeas', 'Mint Coriander Water', 'Tamarind Water'],
    tags: ['Street Style', 'Healthy Version', 'All-Time Favorite'],
    isFeatured: true,
  },

  // --- FRESH PURE JUICES ---
  {
    id: 'm16',
    name: 'Watermelon Juice',
    description: '100% pure, natural, hydrating watermelon juice freshly squeezed and served chilled. Absolutely zero added sugar or water.',
    price: 30,
    image: watermelonJuiceOfficialImg,
    category: 'juices',
    calories: 80,
    protein: 1,
    carbs: 18,
    fats: 0,
    rating: 4.9,
    ingredients: ['100% Fresh Watermelon'],
    tags: ['Pure Hydration', 'No Sugar Added', '100% Fresh', 'Summer Chiller'],
    isFeatured: true,
  },
  {
    id: 'm17',
    name: 'Grape Juice',
    description: 'Freshly extracted sweet and tangy black grape juice, rich in resveratrol and active natural antioxidants.',
    price: 50,
    image: 'https://images.unsplash.com/photo-1595981267035-7b04ec82a897?auto=format&fit=crop&q=80&w=600',
    category: 'juices',
    calories: 120,
    protein: 1,
    carbs: 29,
    fats: 0,
    rating: 4.7,
    ingredients: ['Antioxidant-Rich Black Grapes'],
    tags: ['Heart Healthy', 'Antioxidant Rich', 'Citrus Fresh'],
    isFeatured: false,
  },
  {
    id: 'm18',
    name: 'Karbhuja Juice',
    description: 'Thick, creamy, and satisfyingly sweet fresh muskmelon juice. Naturally rich in potassium and digestive enzymes.',
    price: 50,
    image: 'https://images.unsplash.com/photo-1508888628463-5a8b2996d4ca?auto=format&fit=crop&q=80&w=600',
    category: 'juices',
    calories: 95,
    protein: 1.5,
    carbs: 22,
    fats: 0,
    rating: 4.8,
    ingredients: ['Fresh Sweet Muskmelon'],
    tags: ['Creamy Texture', 'Digestive Aid', 'Pure Fruit'],
    isFeatured: false,
  },
  {
    id: 'm19',
    name: 'Banana Kaaju Juice',
    description: 'An energizing, filling shake blending ripe local bananas with premium cashew nuts (kaaju) and farm-fresh milk.',
    price: 40,
    image: bananaKajuJuiceImg,
    category: 'juices',
    calories: 260,
    protein: 6,
    carbs: 42,
    fats: 7,
    rating: 4.8,
    ingredients: ['Ripe Bananas', 'Premium Cashews', 'Fresh Milk', 'Honey Touch'],
    tags: ['Energy Booster', 'Kaaju Magic', 'Pre-workout'],
    isFeatured: true,
  },
  {
    id: 'm20',
    name: 'Banana Icecream Shake',
    description: 'A decadent yet mindful thick banana shake topped with a scoop of light vanilla ice cream for a delicious weekend treat.',
    price: 50,
    image: bananaIcecreamShakeImg,
    category: 'juices',
    calories: 320,
    protein: 7,
    carbs: 52,
    fats: 9,
    rating: 4.7,
    ingredients: ['Ripe Bananas', 'Fresh Milk', 'Premium Vanilla Ice Cream'],
    tags: ['Sweet Treat', 'Thick & Creamy', 'Delectable'],
    isFeatured: false,
  },
  {
    id: 'm21',
    name: 'Pineapple Juice',
    description: 'Zesty and tangy freshly squeezed tropical pineapple juice. High in Vitamin C and natural anti-inflammatory bromelain.',
    price: 50,
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=600',
    category: 'juices',
    calories: 100,
    protein: 1,
    carbs: 24,
    fats: 0,
    rating: 4.8,
    ingredients: ['Premium Local Pineapple'],
    tags: ['Immunity Booster', 'Bromelain Rich', 'Tropical Burst'],
    isFeatured: false,
  },

  // --- COLD PRESSED PURE JUICES ---
  {
    id: 'm22',
    name: 'ABC Pure Juice',
    description: 'The ultimate health elixir! 100% natural cold-pressed Apple, Beetroot, and Carrot juice. Maximum nutrition retention, no heat processing.',
    price: 80,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600',
    category: 'cold_pressed_juices',
    calories: 140,
    protein: 2,
    carbs: 32,
    fats: 0.5,
    rating: 4.9,
    ingredients: ['Cold-pressed Apple', 'Cold-pressed Beetroot', 'Cold-pressed Carrot'],
    tags: ['Miracle Drink', 'Detox Glow', '100% Pure Cold-Pressed', 'Best Seller'],
    isFeatured: true,
  },
  {
    id: 'm23',
    name: 'Carrot Pure Juice',
    description: 'Rich, unpasteurized cold-pressed sweet carrot juice. Packed with raw minerals, vitamins, and extreme enzymes.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1628556264761-dbb17e4604fc?auto=format&fit=crop&q=80&w=600',
    category: 'cold_pressed_juices',
    calories: 110,
    protein: 1.8,
    carbs: 25,
    fats: 0.2,
    rating: 4.7,
    ingredients: ['100% Raw Cold-Pressed Carrots'],
    tags: ['Vision Booster', 'Enzyme Rich', 'Glowing Skin'],
    isFeatured: false,
  },
  {
    id: 'm24',
    name: 'Beetroot Pure Juice',
    description: 'Pure cold-pressed organic beetroot juice. Perfect for increasing nitric oxide, improving blood flow, and stamina.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587caaec?auto=format&fit=crop&q=80&w=600',
    category: 'cold_pressed_juices',
    calories: 115,
    protein: 2,
    carbs: 26,
    fats: 0.1,
    rating: 4.7,
    ingredients: ['100% Raw Cold-Pressed Beetroots'],
    tags: ['Stamina Booster', 'Blood Cleanser', '100% Organic'],
    isFeatured: false,
  },
  {
    id: 'm25',
    name: 'Mosambi/Battayi Juice',
    description: 'Squeezed cold-pressed Sweet Lime (Mosambi) juice. Bursting with fresh vitamin C and immediate natural hydration.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=600',
    category: 'cold_pressed_juices',
    calories: 90,
    protein: 1.2,
    carbs: 21,
    fats: 0.2,
    rating: 4.9,
    ingredients: ['Fresh Sweet Lime (Mosambi)'],
    tags: ['Vitamin C Blast', 'Electrolyte Refuel', 'Extremely Fresh'],
    isFeatured: true,
  },

  // --- HOT TEA/COFFEE & MILKS ---
  {
    id: 'm26',
    name: 'Tea',
    description: 'Classic hot milk chai prepared with selected Assam tea leaves and milk. Comforting and warm.',
    price: 15,
    image: teaImg,
    category: 'tea_coffee',
    calories: 90,
    protein: 3,
    carbs: 12,
    fats: 3,
    rating: 4.6,
    ingredients: ['Assam Tea Leaves', 'Fresh Milk', 'Sugar'],
    tags: ['Daily Fuel', 'Comfort Cup', 'Aromatic'],
    isFeatured: false,
  },
  {
    id: 'm27',
    name: 'Coffee',
    description: 'A rich and aromatic hot south-Indian style filter coffee brewed with fresh frothy milk.',
    price: 25,
    image: coffeeImg,
    category: 'tea_coffee',
    calories: 110,
    protein: 3.5,
    carbs: 14,
    fats: 3.5,
    rating: 4.8,
    ingredients: ['Filter Coffee Decoction', 'Frothy Milk', 'Sugar'],
    tags: ['Rich Aroma', 'Instant Energy', 'South Indian Style'],
    isFeatured: false,
  },
  {
    id: 'm28',
    name: 'Bellam Tea',
    description: 'Traditional milk tea prepared with organic Jaggery (Bellam) instead of refined sugar. Highly therapeutic and rich in iron.',
    price: 20,
    image: bellamTeaImg,
    category: 'tea_coffee',
    calories: 95,
    protein: 3,
    carbs: 14,
    fats: 3,
    rating: 4.9,
    ingredients: ['Tea Leaves', 'Organic Jaggery (Bellam)', 'Cardamom', 'Ginger', 'Milk'],
    tags: ['No Refined Sugar', 'Iron Rich', 'Highly Demanded', 'Best Seller'],
    isFeatured: true,
  },
  {
    id: 'm29',
    name: 'Badam Tea',
    description: 'Premium hot tea infused with sweet almond powder and loaded with real almond flakes for a rich nutty experience.',
    price: 25,
    image: badamTeaImg,
    category: 'tea_coffee',
    calories: 140,
    protein: 4.5,
    carbs: 16,
    fats: 6,
    rating: 4.8,
    ingredients: ['Tea Leaves', 'Almond Flakes', 'Badam Essence', 'Milk'],
    tags: ['Nutty Sensation', 'Rich & Premium', 'Gourmet Tea'],
    isFeatured: false,
  },
  {
    id: 'm30',
    name: 'Green Tea',
    description: 'Clean organic green tea brewed with hot water, bursting with natural catechins and antioxidants.',
    price: 25,
    image: greenTeaImg,
    category: 'tea_coffee',
    calories: 2,
    protein: 0.2,
    carbs: 0.4,
    fats: 0,
    rating: 4.5,
    ingredients: ['Organic Green Tea Leaves', 'Hot Water'],
    tags: ['Zero Calories', 'Detox Drink', 'Metabolism Boost'],
    isFeatured: false,
  },
  {
    id: 'm31',
    name: 'Horlicks/Boost',
    description: 'Frothy hot milk served with your favorite choice of legacy energy malts: wholesome Horlicks or active Boost!',
    price: 25,
    image: horlicksBoostImg,
    category: 'tea_coffee',
    calories: 160,
    protein: 5,
    carbs: 24,
    fats: 4,
    rating: 4.7,
    ingredients: ['Horlicks/Boost malt', 'Hot Milk', 'Sugar'],
    tags: ['Nostalgic Cup', 'Healthy Malts', 'Warm Comfort'],
    isFeatured: false,
  },
  {
    id: 'm32',
    name: 'Raagi Malt',
    description: 'Highly nutritious hot drink made with slow-roasted Finger Millet (Raagi) powder and milk. Superb source of calcium.',
    price: 25,
    image: ragiMaltImg,
    category: 'tea_coffee',
    calories: 140,
    protein: 5,
    carbs: 22,
    fats: 3,
    rating: 4.9,
    ingredients: ['Organic Finger Millet (Ragi)', 'Warm Milk', 'Organic Jaggery'],
    tags: ['Calcium Packed', 'Superfood Millet', 'Sustained Energy'],
    isFeatured: true,
  },
  {
    id: 'm33',
    name: 'Badam Milk',
    description: 'Fragrant and luxurious chilled milk loaded with almond paste, real saffron threads, and crunchy almond bits.',
    price: 35,
    image: badhamMilkOfficialImg,
    category: 'flavored_milk',
    calories: 210,
    protein: 7,
    carbs: 24,
    fats: 8,
    rating: 4.9,
    ingredients: ['Cold Milk', 'Almond Paste', 'Saffron Threads', 'Cardamom', 'Almond bits'],
    tags: ['Chilled Nectar', 'Saffron Sensation', 'Nutrient Rich', 'Best Seller'],
    isFeatured: true,
  },
  {
    id: 'm34',
    name: 'Rose Milk',
    description: 'Sweet, highly fragrant, and nostalgic chilled pink milk blended with pure organic rose syrup.',
    price: 35,
    image: roseMilkOfficialImg,
    category: 'flavored_milk',
    calories: 180,
    protein: 5,
    carbs: 28,
    fats: 4,
    rating: 4.8,
    ingredients: ['Chilled Milk', 'Organic Rose Syrup'],
    tags: ['Cooler', 'Fragrant Delight', 'Kids Approved'],
    isFeatured: false,
  },

  // --- ALL DAY DESSERTS ---
  {
    id: 'm35',
    name: 'Yogurt with Fruits',
    description: 'Thick, creamy probiotic-rich Greek yogurt topped with fresh chopped bananas, apples, pomegranate pearls, and sweet honey.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=600',
    category: 'desserts',
    calories: 190,
    protein: 8,
    carbs: 32,
    fats: 3,
    rating: 4.8,
    ingredients: ['Probiotic Yogurt', 'Fresh Banana', 'Apple slices', 'Pomegranate', 'Wild Honey'],
    tags: ['Probiotic Rich', 'Fresh Fruits', 'Healthy Dessert'],
    isFeatured: true,
  },
  {
    id: 'm36',
    name: 'Yogurt with Dry Fruits',
    description: 'Velvety high-protein yogurt generously layered with premium almonds, golden cashews, green raisins, and walnuts.',
    price: 70,
    image: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&q=80&w=600',
    category: 'desserts',
    calories: 260,
    protein: 10,
    carbs: 28,
    fats: 11,
    rating: 4.9,
    ingredients: ['Rich Greek Yogurt', 'Almonds', 'Cashew nuts', 'Raisins', 'Walnuts', 'Honey'],
    tags: ['Brain Food', 'Premium Nuts', 'Guilt-Free Sweet'],
    isFeatured: true,
  },
  {
    id: 'm37',
    name: 'Oats with Dry Fruits',
    description: 'Nutritious rolled oats cooked with cream milk, sweetened with organic honey, and finished with a crunchy topping of mixed nuts.',
    price: 50,
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&q=80&w=600',
    category: 'desserts',
    calories: 280,
    protein: 9,
    carbs: 48,
    fats: 6,
    rating: 4.7,
    ingredients: ['Rolled Oats', 'Fresh Milk', 'Almonds', 'Cashews', 'Honey'],
    tags: ['Sustained Carbs', 'Heart Healthy', 'Extremely Filling'],
    isFeatured: false,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'r1',
    name: 'Chaitanya Varma (SRKR ECE)',
    rating: 5,
    comment: 'NutriDelight has completely changed how we eat on campus! The Multi Millet Dosa is unbelievably crispy and the Bellam Tea is absolute heaven after long lectures.',
    date: 'July 5, 2026',
    avatarColor: 'bg-emerald-500',
  },
  {
    id: 'r2',
    name: 'Ramu S. (Gym Trainer, Bhimavaram)',
    rating: 5,
    comment: 'Finally a place in Bhimavaram that does real healthy food. The ABC Cold Pressed juice is pure 100% extract without any added sugar. The chicken sandwich keeps my macros on point!',
    date: 'July 2, 2026',
    avatarColor: 'bg-orange-500',
  },
  {
    id: 'r3',
    name: 'Anjali Patnaik',
    rating: 4.8,
    comment: 'We order the beetroot and carrot dosas every single morning. They are so colorful and my kids love eating them! Highly clean, organic, and delicious.',
    date: 'June 28, 2026',
    avatarColor: 'bg-teal-600',
  },
];
